name: Cron job per day
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Cron job per day
        run: |
          curl --request POST \
          --url 'https://seguro.appsystembrasil.com.br/api/cron'