# .github/workflows/scheduled-builds.yml
name: Verificar seguros

on:
  schedule:
    - cron: '0 6 * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST -d {} https://xcarcorretora.com.br/api/verificarSegurosAtivos